import { ForumRole } from "@prisma/client";

/**
 * Forum visibility type
 *
 * Defines the visibility levels a forum can have:
 * - true (PUBLIC): Visible to all authenticated users
 * - false (PRIVATE): Only visible to forum members
 *
 * Note: The Prisma schema uses 'public_status' as Boolean,
 * so we maintain consistency with that design.
 */
export type ForumVisibility = boolean;

/**
 * Forum role type
 *
 * Re-export ForumRole enum from Prisma for use in the application.
 * Roles:
 * - OWNER: Creator of the forum, has full control
 * - MODERATOR: Can moderate content and manage members
 * - MEMBER: Can post and interact in the forum
 * - VIEWER: Can only view content (read-only access)
 */
export { ForumRole };

/**
 * Create forum request DTO
 *
 * Defines the data structure needed to create a new forum.
 * This type is used after data has been validated by Zod in the controller.
 *
 * Note: Does not include `created_by` because it's obtained from the JWT token.
 * Does not include `forum_id` because it's auto-generated by Prisma.
 */
export interface CreateForumRequest {
  name: string;
  description: string;
  public_status: ForumVisibility;
}

/**
 * Update forum request DTO
 *
 * Defines the fields that can be updated in an existing forum.
 * All fields are optional to allow partial updates.
 */
export interface UpdateForumRequest {
  name?: string;
  description?: string;
  public_status?: ForumVisibility;
  active?: boolean;
}

/**
 * Forum entity
 *
 * Represents the complete structure of a forum as it exists in the database
 * and as returned by Prisma after CRUD operations.
 *
 * This type matches exactly with the `forums` model in schema.prisma.
 */
export interface ForumEntity {
  forum_id: number;
  name: string;
  description: string;
  public_status: boolean;
  created_by: string;
  active: boolean;
  creation_date: Date;
}

/**
 * Forum with creator details
 *
 * Extends ForumEntity to include creator user information.
 * Useful for API responses that need to show who created the forum.
 */
export interface ForumWithCreator extends ForumEntity {
  user: {
    user_id: string;
    name: string;
    parent_last_name: string;
    maternal_last_name: string;
    username: string;
  };
}

/**
 * Forum response DTO
 *
 * Response structure for forum endpoints.
 * Can be used to transform the entity before sending it to the client.
 */
export interface ForumResponse {
  forumId: number;
  name: string;
  description: string;
  isPublic: boolean;
  createdBy: string;
  active: boolean;
  creationDate: Date;
  creator?: {
    userId: string;
    name: string;
    username: string;
  };
}

/**
 * Forum list filters
 *
 * Filter parameters for listing forums.
 * Useful for implementing search and pagination.
 */
export interface ForumListFilters {
  isPublic?: boolean;
  active?: boolean;
  createdBy?: string;
  searchTerm?: string;
  page?: number;
  limit?: number;
}

/**
 * Add user to forum request DTO
 *
 * Defines the data needed to add a user to a forum.
 */
export interface AddUserToForumRequest {
  user_id: string;
  forum_role: ForumRole;
}

/**
 * Update forum member role request DTO
 *
 * Defines the data needed to update a user's role in a forum.
 */
export interface UpdateForumMemberRoleRequest {
  forum_role: ForumRole;
}

/**
 * Forum member entity
 *
 * Represents a user's membership in a forum.
 */
export interface ForumMemberEntity {
  user_id: string;
  forum_id: number;
  forum_role: ForumRole;
}

/**
 * Forum member with user details
 *
 * Extends ForumMemberEntity to include user information.
 */
export interface ForumMemberWithDetails extends ForumMemberEntity {
  user: {
    user_id: string;
    name: string;
    parent_last_name: string;
    maternal_last_name: string;
    username: string;
  };
}

export type Message = {
  _count: { messages: number; likes: number };
  message_id: number;
  content: string;
  publication_timestamp: Date;
  forum: { name: string; forum_id: number };
};

export type ParsedMessage = {
  messageId: number;
  content: string;
  likes: number;
  replies: number;
  forums: { forumId: number; name: string };
};
